[workspace]
resolver = "2"
members = [
  "contracts/blackjack/host",
  "contracts/blackjack/contract",
  "contracts/blackjack/methods",
  "server",
]

[workspace.dependencies]
# don't forget to update methods/guest/Cargo.toml 
sdk = { git = "https://github.com/hyle-org/hyle", package = "hyle-contract-sdk", branch = "refacto/multiproof" }
client-sdk = { git = "https://github.com/hyle-org/hyle", default-features = false, package = "hyle-client-sdk", branch = "refacto/multiproof" }
hyle = { git = "https://github.com/Hyle-org/hyle.git", package = "hyle", branch = "refacto/multiproof" }
hyle_hyllar = { git = "https://github.com/Hyle-org/hyle.git", package = "hyle-hyllar", branch = "refacto/multiproof" }
contract = { path = "contracts/blackjack/contract", package = "contract" }

[workspace.package]
version = "0.4.1"
edition = "2021"
homepage = "https://hyle.eu/"
repository = "https://github.com/Hyle-org/ezcasino/"
# licence = ""
